import { Component } from '@angular/core';

@Component({
  selector: 'app-diagnostico',
  templateUrl: './diagnostico.component.html',
  styleUrls: ['./diagnostico.component.css']
})
export class DiagnosticoComponent {
  conceptos:boolean=false;
  gestion:boolean=false;
  productividad:boolean=false;
  operacional:boolean=false;
  calidad:boolean=false;
  innovacion:boolean=false;
  financiero:boolean=false;
  logistica:boolean=false;
  digital:boolean=false;
  ambiental:boolean=false;
  intelectual:boolean=false;
  consolidado:boolean=false;

  condicionConceptos(){
    if(this.conceptos){
      this.conceptos=false;
    }else{
      this.conceptos=true;
    }
  }
  condicionGestion(){
    if(this.gestion){
      this.gestion=false;
    }else{
      this.gestion=true;
    }
  }
  condicionProductividad(){
    if(this.productividad){
      this.productividad=false;
    }else{
      this.productividad=true;
    }
  }
  condicionOperacional(){
    if(this.operacional){
      this.operacional=false;
    }else{
      this.operacional=true;
    }
  }
  condicionCalidad(){
    if(this.calidad){
      this.calidad=false;
    }else{
      this.calidad=true;
    }
  }
  condicionInnovacion(){
    if(this.innovacion){
      this.innovacion=false;
    }else{
      this.innovacion=true;
    }
  }
  condicionFinanciero(){
    if(this.financiero){
      this.financiero=false;
    }else{
      this.financiero=true;
    }
  }
  condicionLogistica(){
    if(this.logistica){
      this.logistica=false;
    }else{
      this.logistica=true;
    }
  }
  condicionDigitalizacion(){
    if(this.digital){
      this.digital=false;
    }else{
      this.digital=true;
    }
  }
  condicionAmbiental(){
    if(this.ambiental){
      this.ambiental=false;
    }else{
      this.ambiental=true;
    }
  }
  condicionIntelectual(){
    if(this.intelectual){
      this.intelectual=false;
    }else{
      this.intelectual=true;
    }
  }
  condicionConsolidado(){
    if(this.consolidado){
      this.consolidado=false;
    }else{
      this.consolidado=true;
    }
  }
}
